# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 公考加油站
subtitle: '为上岸而战'
description: '记录个人备考心得'
keywords: 程序员,公务员,考公,博客
author: Holmofy
language: zh-cn
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://posts.gwy.hufeifei.cn
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - ads.txt
  - "google4b244692104f4e5f.html"
  - "baidu_verify_code-rhdRGmATQV.html"
  - "webpushr-sw.js"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: 
    - www.hufeifei.cn
    - blog.hufeifei.cn
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
# https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom ##feed类型 atom或者rss2
  path: atom.xml ##feed路径
  limit: 20 ##feed文章最小数量
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: xoxo

plugins:
  - hexo-generator-feed
  - hexo-generator-sitemap
  - hexo-generator-baidu-sitemap
  - hexo-filter-mathjax

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
# Deployment
## Docs: https://hexo.io/docs/deployment.html
## 这里使用git部署网站
deploy:
  type: git
  repo: git@posts.gwy.hufeifei.cn:repo/posts.gwy.hufeifei.cn.git
  branch: master
  message: "hexo deployment: {{ now('YYYY-MM-DD HH:mm:ss') }}"

# 配置Math.js
mathjax:
  tags: none # or 'ams' or 'all'
  single_dollars: true # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9 # relative CJK char width
  normal_width: 0.6 # relative normal (monospace) width
  append_css: true # add CSS to pages rendered by MathJax
  every_page: false # if true, every page will be rendered by MathJax regardless the `mathjax` setting in Front-matter

toc:
  maxdepth: 3
  class: toc
  slugify: transliteration
  decodeEntities: false
  anchor: false

sitemap:
  path: sitemap.xml
  #template: ./sitemap_template.xml
  rel: true
  tags: true
  categories: true

# https://github.com/hexojs/hexo-filter-nofollow
# 解决图片外链的问题
nofollow:
  enable: true
  elements: ["img"]
  field: post
  include:
    - "img.draveness.me"
    - "duanple.com"
    - "*.zhiimg.com"
    - "*.cdn.sohucs.com"
    - "*.infoq.cn"
  rel:
    - 'external'
    - 'noreferrer'
    - 'nofollow'
    - 'noopener'
  referrerpolicy: 'no-referrer'


# https://github.com/miao1007/hexo-filter-plantuml
# 添加plantuml的支持
plantuml:
  #  Local or PlantUMLServer.
  render: "PlantUMLServer"
  # The render server, you can also create your self-hosting sever
  # self-hosting cmd: java -jar /usr/local/Cellar/plantuml/1.2021.5/libexec/plantuml.jar -picoweb
  # server: http://localhost:8080/plantuml
  server: "http://www.plantuml.com/plantuml"
  # "inline": <svg>xxx<svg/>
  # "inlineUrlEncode": <img src='data:image/svg+xml;> 
  # "inlineBase64": <img src='data:image/svg+xml;base64> 
  # "localLink": <img src="/assert/puml/xxxx.svg">
  # "externalLink": <img src="http://www.plantuml.com/plantuml/svg/xxx">
  link: "inline"
